/* RUNTIME TCG — 카드 일러스트 매핑(매니페스트). dev.html 이 자동 관리. */
/* 값: "art/x.webp" 또는 { src, pos:"50% 50%", fit:"cover"|"contain" } */
window.RT_ART = {
  "Affinity": { src: "art/Affinity.png", pos: "46% 45%", fit: "contain" },
  "Async": { src: "art/Async.png", pos: "50% 50%", fit: "contain" },
  "Atomic": { src: "art/Atomic.png", pos: "65% 35%", fit: "cover" },
  "Bedrock": { src: "art/Bedrock.png", pos: "50% 33%", fit: "cover" },
  "Bit": { src: "art/Bit.png", pos: "50% 50%", fit: "contain" },
  "Bool": { src: "art/Bool.png", pos: "50% 50%", fit: "contain" },
  "Branch": "art/Branch.png",
  "Broadcast": { src: "art/Broadcast.png", pos: "50% 50%", fit: "contain" },
  "Buffer": { src: "art/Buffer.png", pos: "50% 50%", fit: "contain" },
  "Byte": "art/Byte.png",
  "Cache": { src: "art/Cache.png", pos: "50% 50%", fit: "contain" },
  "Callback": { src: "art/Callback.png", pos: "36% 66%", fit: "contain" },
  "Canary": { src: "art/Canary.png", pos: "50% 80%", fit: "cover" },
  "Cannon": { src: "art/Cannon.png", pos: "76% 73%", fit: "cover" },
  "Checksum": { src: "art/Checksum.png", pos: "54% 31%", fit: "cover" },
  "Cluster": { src: "art/Cluster.png", pos: "54% 11%", fit: "contain" },
  "Coerce": { src: "art/Coerce.png", pos: "40% 30%", fit: "cover" },
  "Collector": { src: "art/Collector.png", pos: "50% 50%", fit: "contain" },
  "Compile": { src: "art/Compile.png", pos: "51% 14%", fit: "cover" },
  "Cond": { src: "art/Cond.png", pos: "50% 50%", fit: "contain" },
  "Conduit": "art/Conduit.png",
  "Const": { src: "art/Const.png", pos: "50% 50%", fit: "contain" },
  "Cron": { src: "art/Cron.png", pos: "57% 23%", fit: "cover" },
  "Cursor": { src: "art/Cursor.png", pos: "50% 50%", fit: "contain" },
  "Daemon": { src: "art/Daemon.png", pos: "47% 46%", fit: "cover" },
  "Debug": { src: "art/Debug.png", pos: "50% 50%", fit: "contain" },
  "Delete": { src: "art/Delete.png", pos: "54% 33%", fit: "cover" },
  "Dispatch": { src: "art/Dispatch.png", pos: "50% 13%", fit: "cover" },
  "Exec": { src: "art/Exec.png", pos: "53% 5%", fit: "cover" },
  "Exploit": { src: "art/Exploit.png", pos: "32% 68%", fit: "contain" },
  "Fault": { src: "art/Fault.png", pos: "57% 55%", fit: "cover" },
  "Fiber": { src: "art/Fiber.png", pos: "73% 4%", fit: "cover" },
  "Firewall": { src: "art/Firewall.png", pos: "45% 19%", fit: "cover" },
  "Flag": { src: "art/Flag.png", pos: "50% 50%", fit: "contain" },
  "Forkbomb": { src: "art/Forkbomb.png", pos: "50% 50%", fit: "contain" },
  "Guard": { src: "art/Guard.png", pos: "47% 27%", fit: "cover" },
  "HalfClone": "art/HalfClone.png",
  "Heap": "art/Heap.png",
  "Hivemind": { src: "art/Hivemind.png", pos: "53% 59%", fit: "cover" },
  "Honeypot": { src: "art/Honeypot.png", pos: "47% 9%", fit: "cover" },
  "Hook": { src: "art/Hook.png", pos: "54% 93%", fit: "contain" },
  "Hotfix": { src: "art/Hotfix.png", pos: "50% 50%", fit: "contain" },
  "Idle": { src: "art/Idle.png", pos: "43% 79%", fit: "cover" },
  "Inline": { src: "art/Inline.png", pos: "50% 50%", fit: "contain" },
  "Int": { src: "art/Int.png", pos: "50% 50%", fit: "contain" },
  "Interrupt": { src: "art/Interrupt.png", pos: "65% 42%", fit: "cover" },
  "JIT": { src: "art/JIT.png", pos: "56% 14%", fit: "cover" },
  "Join": "art/Join.png",
  "Journal": { src: "art/Journal.png", pos: "50% 50%", fit: "contain" },
  "Jump": { src: "art/Jump.png", pos: "50% 50%", fit: "contain" },
  "Kernel": { src: "art/Kernel.png", pos: "65% 49%", fit: "cover" },
  "Lambda": { src: "art/Lambda.png", pos: "50% 50%", fit: "contain" },
  "Latch": { src: "art/Latch.png", pos: "35% 56%", fit: "contain" },
  "Livelock": { src: "art/Livelock.png", pos: "39% 61%", fit: "cover" },
  "Longjmp": { src: "art/Longjmp.png", pos: "50% 50%", fit: "contain" },
  "Loop": "art/Loop.png",
  "Mainframe": { src: "art/Mainframe.png", pos: "49% 87%", fit: "cover" },
  "Marshal": "art/Marshal.png",
  "Merge": "art/Merge.png",
  "Mutex": { src: "art/Mutex.png", pos: "50% 50%", fit: "contain" },
  "Noop": "art/Noop.png",
  "Null": "art/Null.png",
  "Offset": { src: "art/Offset.png", pos: "50% 50%", fit: "contain" },
  "Overflow": { src: "art/Overflow.png", pos: "53% 7%", fit: "cover" },
  "Overlord": { src: "art/Overlord.png", pos: "50% 50%", fit: "contain" },
  "Overrun": { src: "art/Overrun.png", pos: "50% 50%", fit: "contain" },
  "Page": { src: "art/Page.png", pos: "56% 66%", fit: "cover" },
  "Panic": { src: "art/Panic.png", pos: "50% 52%", fit: "cover" },
  "Persist": { src: "art/Persist.png", pos: "50% 40%", fit: "contain" },
  "Pin": { src: "art/Pin.png", pos: "50% 50%", fit: "contain" },
  "Pipe": { src: "art/Pipe.png", pos: "59% 47%", fit: "cover" },
  "Pivot": { src: "art/Pivot.png", pos: "50% 50%", fit: "contain" },
  "Polymorph": { src: "art/Polymorph.png?v=122", pos: "50% 50%", fit: "contain" },
  "Pool": { src: "art/Pool.png", pos: "50% 50%", fit: "contain" },
  "Predicate": { src: "art/Predicate.png", pos: "50% 50%", fit: "contain" },
  "Preempt": { src: "art/Preempt.png", pos: "79% 50%", fit: "cover" },
  "Probe": { src: "art/Probe.png", pos: "49% 25%", fit: "contain" },
  "Profiler": { src: "art/Profiler.png", pos: "48% 49%", fit: "contain" },
  "ROM": "art/ROM.png",
  "Race": { src: "art/Race.png", pos: "36% 53%", fit: "contain" },
  "Raycast": { src: "art/Raycast.png", pos: "62% 59%", fit: "cover" },
  "Recursion": { src: "art/Recursion.png", pos: "56% 29%", fit: "cover" },
  "Register": { src: "art/Register.png", pos: "52% 42%", fit: "cover" },
  "Relay": { src: "art/Relay.png", pos: "52% 4%", fit: "cover" },
  "Replica": "art/Replica.png",
  "Reroute": { src: "art/Reroute.png", pos: "50% 50%", fit: "contain" },
  "Ripple": { src: "art/Ripple.png", pos: "43% 39%", fit: "cover" },
  "Salvo": { src: "art/Salvo.png", pos: "50% 50%", fit: "contain" },
  "Sandbox": { src: "art/Sandbox.png", pos: "50% 50%", fit: "contain" },
  "Scheduler": { src: "art/Scheduler.png", pos: "50% 50%", fit: "contain" },
  "Semaphore": { src: "art/Semaphore.png", pos: "59% 19%", fit: "contain" },
  "Sentinel": { src: "art/Sentinel.png", pos: "49% 46%", fit: "cover" },
  "Signal": "art/Signal.png",
  "Singleton": { src: "art/Singleton.png", pos: "50% 50%", fit: "contain" },
  "Singularity": "art/Singularity.png",
  "Snapshot": "art/Snapshot.png",
  "Sonar": { src: "art/Sonar.png", pos: "48% 40%", fit: "cover" },
  "Spike": { src: "art/Spike.png", pos: "48% 14%", fit: "cover" },
  "Spooler": { src: "art/Spooler.png", pos: "68% 40%", fit: "cover" },
  "Stack": "art/Stack.png",
  "Stub": { src: "art/Stub.png", pos: "50% 50%", fit: "contain" },
  "Sudo": "art/Sudo.png",
  "Surge": { src: "art/Surge.png", pos: "42% 67%", fit: "contain" },
  "Sweeper": { src: "art/Sweeper.png", pos: "42% 81%", fit: "contain" },
  "Switch": { src: "art/Switch.png", pos: "50% 50%", fit: "contain" },
  "Symlink": "art/Symlink.png",
  "TLS": { src: "art/TLS.png", pos: "87% 39%", fit: "cover" },
  "Thrash": { src: "art/Thrash.png", pos: "67% 39%", fit: "cover" },
  "Token1": { src: "art/Token.png", pos: "51% 39%", fit: "cover" },
  "Token2": { src: "art/Token2.png", pos: "50% 50%", fit: "contain" },
  "Token21": { src: "art/Token2.png", pos: "50% 50%", fit: "contain" },
  "Token2b": { src: "art/Token2b.png", pos: "50% 50%", fit: "contain" },
  "Token5": { src: "art/Token5.png", pos: "50% 50%", fit: "contain" },
  "Trap": { src: "art/Trap.png", pos: "55% 51%", fit: "cover" },
  "Value": { src: "art/Value.png", pos: "50% 50%", fit: "contain" },
  "Var": { src: "art/Var.png", pos: "53% 15%", fit: "cover" },
  "Vector": { src: "art/Vector.png", pos: "80% 52%", fit: "cover" },
  "Wall10": { src: "art/Wall10.png", pos: "50% 6%", fit: "cover" },
  "Wall5": { src: "art/Wall5.png", pos: "45% 31%", fit: "cover" },
  "Wall8": { src: "art/Wall8.png", pos: "56% 35%", fit: "cover" },
  "Ward": { src: "art/Ward.png", pos: "50% 50%", fit: "contain" },
  "Watchdog": { src: "art/Watchdog.png", pos: "50% 50%", fit: "contain" },
  "Worker": { src: "art/Worker.png", pos: "50% 50%", fit: "contain" },
  "Wormhole": { src: "art/Wormhole.png", pos: "50% 50%", fit: "contain" },
  "Zygote": { src: "art/Zygote.png", pos: "54% 25%", fit: "cover" },
  "__body0": { src: "art/__body0.png", pos: "50% 50%", fit: "contain" },
  "__body1": { src: "art/__body1.png", pos: "50% 50%", fit: "contain" },
  "__wall": { src: "art/__wall.png", pos: "51% 38%", fit: "cover" },
  "amplify()": "art/amplify_fn.png",
  "assert()": { src: "art/assert_fn.png", pos: "69% 79%", fit: "cover" },
  "barrier()": { src: "art/barrier_fn.png", pos: "49% 17%", fit: "cover" },
  "bind()": { src: "art/bind_fn.png", pos: "50% 87%", fit: "contain" },
  "boost()": { src: "art/boost_fn.png", pos: "50% 50%", fit: "contain" },
  "burst()": { src: "art/burst_fn.png", pos: "77% 64%", fit: "cover" },
  "cast()": { src: "art/cast_fn.png", pos: "56% 24%", fit: "cover" },
  "catch()": { src: "art/catch_fn.png", pos: "54% 16%", fit: "cover" },
  "chain()": { src: "art/chain_fn.png", pos: "49% 39%", fit: "cover" },
  "clear()": { src: "art/clear_fn.png", pos: "64% 57%", fit: "cover" },
  "coalesce()": { src: "art/coalesce_fn.png", pos: "55% 30%", fit: "cover" },
  "compact()": { src: "art/compact_fn.png", pos: "53% 72%", fit: "cover" },
  "copy()": "art/copy_fn.png",
  "crash()": { src: "art/crash_fn.png", pos: "88% 66%", fit: "cover" },
  "defer()": { src: "art/defer_fn.png", pos: "50% 50%", fit: "contain" },
  "defrag()": "art/defrag_fn.png",
  "drop()": "art/drop_fn.png",
  "echo()": "art/echo_fn.png",
  "exit()": { src: "art/exit_fn.png", pos: "50% 50%", fit: "contain" },
  "fanout()": "art/fanout_fn.png",
  "flush()": { src: "art/flush_fn.png", pos: "55% 41%", fit: "cover" },
  "fork()": { src: "art/fork_fn.png", pos: "50% 50%", fit: "contain" },
  "fortify()": { src: "art/fortify_fn.png?v=122", pos: "50% 50%", fit: "contain" },
  "free()": "art/free_fn.png",
  "freeze()": { src: "art/freeze_fn.png", pos: "38% 33%", fit: "cover" },
  "glitch()": { src: "art/glitch_fn.png", pos: "52% 38%", fit: "cover" },
  "goto()": { src: "art/goto_fn.png", pos: "65% 87%", fit: "cover" },
  "grep()": { src: "art/grep_fn.png?v=122", pos: "50% 50%", fit: "contain" },
  "halt()": { src: "art/halt_fn.png", pos: "50% 50%", fit: "contain" },
  "hop()": { src: "art/hop_fn.png", pos: "48% 53%", fit: "cover" },
  "inject()": { src: "art/inject_fn.png", pos: "50% 50%", fit: "contain" },
  "jitter()": { src: "art/jitter_fn.png", pos: "66% 15%", fit: "cover" },
  "jolt()": { src: "art/jolt_fn.png", pos: "45% 51%", fit: "contain" },
  "kill()": { src: "art/kill_fn.png?v=122", pos: "50% 50%", fit: "contain" },
  "lock()": { src: "art/lock_fn.png", pos: "50% 50%", fit: "contain" },
  "log()": { src: "art/log_fn.png", pos: "60% 61%", fit: "cover" },
  "malloc()": { src: "art/malloc_fn.png", pos: "50% 90%", fit: "cover" },
  "memcpy()": { src: "art/memcpy_fn.png", pos: "50% 50%", fit: "contain" },
  "mend()": { src: "art/mend_fn.png", pos: "48% 44%", fit: "cover" },
  "migrate()": { src: "art/migrate_fn.png", pos: "50% 50%", fit: "contain" },
  "mmap()": { src: "art/mmap_fn.png", pos: "50% 50%", fit: "contain" },
  "mprotect()": { src: "art/mprotect_fn.png", pos: "50% 50%", fit: "contain" },
  "overclock()": { src: "art/overclock_fn.png", pos: "57% 50%", fit: "cover" },
  "overtime()": { src: "art/overtime.png", pos: "51% 49%", fit: "cover" },
  "patch()": "art/patch_fn.png",
  "ping()": { src: "art/ping_fn.png", pos: "50% 50%", fit: "contain" },
  "pipeline()": { src: "art/pipeline_fn.png", pos: "50% 50%", fit: "contain" },
  "proxy()": "art/proxy_fn.png",
  "pull()": { src: "art/pull_fn.png", pos: "54% 53%", fit: "cover" },
  "purge()": { src: "art/purge_fn.png", pos: "55% 54%", fit: "cover" },
  "push()": { src: "art/push_fn.png", pos: "56% 31%", fit: "cover" },
  "reap()": { src: "art/reap_fn.png", pos: "30% 59%", fit: "contain" },
  "reflect()": { src: "art/reflect_fn.png", pos: "50% 50%", fit: "contain" },
  "restore()": "art/restore_fn.png",
  "retry()": { src: "art/retry_fn.png", pos: "50% 50%", fit: "contain" },
  "rotate()": { src: "art/rotate_fn.png", pos: "50% 50%", fit: "contain" },
  "rush()": { src: "art/rush_fn.png", pos: "50% 50%", fit: "contain" },
  "segfault()": { src: "art/segfault_fn.png", pos: "39% 60%", fit: "contain" },
  "shift()": { src: "art/shift_fn.png", pos: "50% 50%", fit: "contain" },
  "siphon()": { src: "art/siphon_fn.png", pos: "50% 50%", fit: "contain" },
  "snipe()": { src: "art/snipe_fn.png", pos: "50% 50%", fit: "contain" },
  "spawn()": { src: "art/spawn_fn.png", pos: "57% 9%", fit: "contain" },
  "splice()": { src: "art/splice_fn.png", pos: "50% 50%", fit: "contain" },
  "strike()": "art/strike_fn.png",
  "suspend()": { src: "art/suspend_fn.png", pos: "50% 50%", fit: "contain" },
  "swap()": { src: "art/swap_fn.png", pos: "50% 50%", fit: "contain" },
  "swapfile()": { src: "art/swapfile_fn.png", pos: "49% 34%", fit: "contain" },
  "sync()": "art/sync_fn.png",
  "throw()": { src: "art/throw_fn.png", pos: "50% 50%", fit: "contain" },
  "trace()": { src: "art/trace_fn.png", pos: "53% 33%", fit: "cover" },
  "volt()": { src: "art/volt_fn.png", pos: "50% 6%", fit: "cover" },
  "wait()": "art/wait_fn.png",
  "wall()": { src: "art/wall_fn.png", pos: "55% 24%", fit: "cover" },
  "yield()": { src: "art/yield_fn.png?v=122", pos: "50% 50%", fit: "contain" },
  // v10 확장 — Switch 계열·If·보호 신규 카드 + 변신폼(form)
  "Adaptive": { src: "art/Adaptive.png", pos: "50% 50%", fit: "contain" },
  "Failover": { src: "art/Failover.png", pos: "50% 50%", fit: "contain" },
  "Morph": { src: "art/Morph.png", pos: "50% 50%", fit: "contain" },
  "Duplex": { src: "art/Duplex.png", pos: "50% 50%", fit: "contain" },
  "Toggle": { src: "art/Toggle.png", pos: "50% 50%", fit: "contain" },
  "Ternary": { src: "art/Ternary.png", pos: "50% 50%", fit: "contain" },
  "Elif": { src: "art/Elif.png", pos: "50% 50%", fit: "contain" },
  "Match": { src: "art/Match.png?v=122", pos: "50% 50%", fit: "contain" },
  "Assert": { src: "art/Assert.png", pos: "50% 50%", fit: "contain" },
  "Fallback": { src: "art/Fallback.png", pos: "50% 50%", fit: "contain" },
  "Case": { src: "art/Case.png", pos: "50% 50%", fit: "contain" },
  "Aegis": { src: "art/Aegis.png", pos: "50% 50%", fit: "contain" },
  "Bulwark": { src: "art/Bulwark.png", pos: "50% 50%", fit: "contain" },
  "Sentry": { src: "art/Sentry.png", pos: "50% 50%", fit: "contain" },
  "Quarantine": { src: "art/Quarantine.png", pos: "50% 50%", fit: "contain" },
  "Warden": { src: "art/Warden.png", pos: "50% 50%", fit: "contain" },
  "shield()": { src: "art/shield_fn.png", pos: "50% 50%", fit: "contain" },
  "bastion()": { src: "art/bastion_fn.png", pos: "50% 50%", fit: "contain" },
  "harden()": { src: "art/harden_fn.png", pos: "50% 50%", fit: "contain" },
  "Switch_ATK": { src: "art/Switch_ATK.png", pos: "50% 50%", fit: "contain" },
  "Switch_DEF": { src: "art/Switch_DEF.png", pos: "50% 50%", fit: "contain" },
  "Adaptive_ATK": { src: "art/Adaptive_ATK.png", pos: "50% 50%", fit: "contain" },
  "Adaptive_DEF": { src: "art/Adaptive_DEF.png", pos: "50% 50%", fit: "contain" },
  "Failover_STBY": { src: "art/Failover_STBY.png?v=122", pos: "50% 50%", fit: "contain" },
  "Failover_ACT": { src: "art/Failover_ACT.png?v=122", pos: "50% 50%", fit: "contain" },
  "Morph_MELEE": { src: "art/Morph_MELEE.png", pos: "50% 50%", fit: "contain" },
  "Morph_RANGE": { src: "art/Morph_RANGE.png", pos: "50% 50%", fit: "contain" },
  "Duplex_TX": { src: "art/Duplex_TX.png?v=122", pos: "50% 50%", fit: "contain" },
  "Duplex_RX": { src: "art/Duplex_RX.png?v=122", pos: "50% 50%", fit: "contain" },
  "Toggle_HI": { src: "art/Toggle_HI.png", pos: "50% 50%", fit: "contain" },
  "Toggle_LO": { src: "art/Toggle_LO.png", pos: "50% 50%", fit: "contain" },
  "Fused": { src: "art/Fused.png?v=122", pos: "50% 50%", fit: "contain" },
};
