/* RUNTIME TCG — 카드 일러스트 매핑(매니페스트). dev.html 이 자동 관리. */
/* 값: "art/x.webp" 또는 { src, pos:"50% 50%", fit:"cover"|"contain" } */
window.RT_ART = {
  "Async": "art/Async.png",
  "Bedrock": "art/Bedrock.png",
  "Bit": "art/Bit.png",
  "Bool": "art/Bool.png",
  "Buffer": "art/Buffer.png",
  "Byte": "art/Byte.png",
  "Cache": "art/Cache.png",
  "Callback": "art/Callback.png",
  "Cannon": { src: "art/Cannon.png", pos: "44% 56%", fit: "cover" },
  "Coerce": "art/Coerce.png",
  "Compile": "art/Compile.png",
  "Conduit": { src: "art/Conduit.png", pos: "48% 13%", fit: "cover" },
  "Const": "art/Const.png",
  "Cursor": "art/Cursor.png",
  "Daemon": "art/Daemon.png",
  "Delete": "art/Delete.png",
  "Exec": "art/Exec.png",
  "Exploit": "art/Exploit.png",
  "Fiber": { src: "art/Fiber.png", pos: "50% 9%", fit: "cover" },
  "Firewall": "art/Firewall.png",
  "Flag": "art/Flag.png",
  "HalfClone": "art/HalfClone.png",
  "Heap": "art/Heap.png",
  "Hivemind": "art/Hivemind.png",
  "Hook": "art/Hook.png",
  "Hotfix": "art/Hotfix.png",
  "Idle": "art/Idle.png",
  "Inline": "art/Inline.png",
  "Int": "art/Int.png",
  "Interrupt": "art/Interrupt.png",
  "Jump": "art/Jump.png",
  "Kernel": "art/Kernel.png",
  "Lambda": "art/Lambda.png",
  "Longjmp": "art/Longjmp.png",
  "Loop": "art/Loop.png",
  "Mainframe": "art/Mainframe.png",
  "Merge": "art/Merge.png",
  "Mutex": "art/Mutex.png",
  "Noop": "art/Noop.png",
  "Null": "art/Null.png",
  "Overflow": { src: "art/Overflow.png", pos: "51% 12%", fit: "cover" },
  "Overlord": "art/Overlord.png",
  "Overrun": { src: "art/Overrun.png", pos: "56% 66%", fit: "cover" },
  "Page": "art/Page.png",
  "Panic": "art/Panic.png",
  "Persist": { src: "art/Persist.png", pos: "50% 40%", fit: "cover" },
  "Pin": "art/Pin.png",
  "Pipe": "art/Pipe.png",
  "Pivot": "art/Pivot.png",
  "Polymorph": "art/Polymorph.png",
  "Probe": "art/Probe.png",
  "Profiler": { src: "art/Profiler.png", pos: "51% 92%", fit: "cover" },
  "Race": "art/Race.png",
  "Raycast": "art/Raycast.png",
  "Recursion": "art/Recursion.png",
  "Register": "art/Register.png",
  "Relay": "art/Relay.png",
  "Replica": "art/Replica.png",
  "Reroute": "art/Reroute.png",
  "Ripple": "art/Ripple.png",
  "Salvo": "art/Salvo.png",
  "Semaphore": "art/Semaphore.png",
  "Sentinel": "art/Sentinel.png",
  "Signal": "art/Signal.png",
  "Singleton": "art/Singleton.png",
  "Singularity": "art/Singularity.png",
  "Sonar": "art/Sonar.png",
  "Spike": "art/Spike.png",
  "Stack": "art/Stack.png",
  "Stub": "art/Stub.png",
  "Surge": { src: "art/Surge.png", pos: "51% 67%", fit: "cover" },
  "Sweeper": "art/Sweeper.png",
  "Token": "art/Token.png",
  "Token2": "art/Token2.png",
  "Token2b": "art/Token2b.png",
  "Token5": "art/Token5.png",
  "Trap": "art/Trap.png",
  "Value": "art/Value.png",
  "Var": "art/Var.png",
  "Vector": "art/Vector.png",
  "Wall10": "art/Wall10.png",
  "Wall8": "art/Wall8.png",
  "Ward": "art/Ward.png",
  "Watchdog": "art/Watchdog.png",
  "Worker": "art/Worker.png",
  "Zygote": "art/Zygote.png",
  "__body0": "art/__body0.png",
  "__body1": "art/__body1.png",
  "amplify()": "art/amplify_fn.png",
  "assert()": "art/assert_fn.png",
  "barrier()": "art/barrier_fn.png",
  "bind()": "art/bind_fn.png",
  "boost()": "art/boost_fn.png",
  "burst()": "art/burst_fn.png",
  "cast()": "art/cast_fn.png",
  "catch()": "art/catch_fn.png",
  "chain()": "art/chain_fn.png",
  "clear()": "art/clear_fn.png",
  "compact()": "art/compact_fn.png",
  "copy()": "art/copy_fn.png",
  "crash()": "art/crash_fn.png",
  "drop()": "art/drop_fn.png",
  "echo()": "art/echo_fn.png",
  "exit()": "art/exit_fn.png",
  "flush()": "art/flush_fn.png",
  "fork()": "art/fork_fn.png",
  "fortify()": "art/fortify_fn.png",
  "free()": "art/free_fn.png",
  "freeze()": "art/freeze_fn.png",
  "glitch()": "art/glitch_fn.png",
  "goto()": "art/goto_fn.png",
  "grep()": "art/grep_fn.png",
  "inject()": "art/inject_fn.png",
  "kill()": "art/kill_fn.png",
  "lock()": "art/lock_fn.png",
  "malloc()": "art/malloc_fn.png",
  "memcpy()": "art/memcpy_fn.png",
  "mend()": "art/mend_fn.png",
  "overclock()": "art/overclock_fn.png",
  "patch()": "art/patch_fn.png",
  "ping()": "art/ping_fn.png",
  "proxy()": "art/proxy_fn.png",
  "pull()": "art/pull_fn.png",
  "purge()": "art/purge_fn.png",
  "push()": "art/push_fn.png",
  "reflect()": "art/reflect_fn.png",
  "restore()": "art/restore_fn.png",
  "rush()": "art/rush_fn.png",
  "segfault()": { src: "art/segfault_fn.png", pos: "59% 57%", fit: "cover" },
  "shift()": "art/shift_fn.png",
  "siphon()": "art/siphon_fn.png",
  "snipe()": "art/snipe_fn.png",
  "spawn()": "art/spawn_fn.png",
  "strike()": "art/strike_fn.png",
  "swap()": "art/swap_fn.png",
  "sync()": "art/sync_fn.png",
  "throw()": "art/throw_fn.png",
  "trace()": "art/trace_fn.png",
  "volt()": { src: "art/volt_fn.png", pos: "50% 6%", fit: "cover" },
  "wait()": "art/wait_fn.png",
  "wall()": "art/wall_fn.png",
  "yield()": "art/yield_fn.png",
};
