/* RUNTIME TCG — 카드 일러스트 매핑(매니페스트). dev.html 이 자동 관리. */
/* 값: "art/x.webp" 또는 { src, pos:"50% 50%", fit:"cover"|"contain" } */
window.RT_ART = {
  "Affinity": { src: "art/Affinity.png", pos: "46% 45%", fit: "contain" },
  "Async": "art/Async.png",
  "Atomic": { src: "art/Atomic.png", pos: "65% 35%", fit: "cover" },
  "Bedrock": "art/Bedrock.png",
  "Bit": "art/Bit.png",
  "Bool": "art/Bool.png",
  "Branch": "art/Branch.png",
  "Broadcast": "art/Broadcast.png",
  "Buffer": "art/Buffer.png",
  "Byte": "art/Byte.png",
  "Cache": "art/Cache.png",
  "Callback": "art/Callback.png",
  "Canary": "art/Canary.png",
  "Cannon": { src: "art/Cannon.png", pos: "44% 56%", fit: "cover" },
  "Checksum": "art/Checksum.png",
  "Cluster": { src: "art/Cluster.png", pos: "54% 11%", fit: "contain" },
  "Coerce": "art/Coerce.png",
  "Collector": "art/Collector.png",
  "Compile": { src: "art/Compile.png", pos: "50% 50%", fit: "contain" },
  "Cond": "art/Cond.png",
  "Conduit": { src: "art/Conduit.png", pos: "48% 13%", fit: "cover" },
  "Const": "art/Const.png",
  "Cron": "art/Cron.png",
  "Cursor": "art/Cursor.png",
  "Daemon": "art/Daemon.png",
  "Debug": "art/Debug.png",
  "Delete": "art/Delete.png",
  "Dispatch": "art/Dispatch.png",
  "Exec": { src: "art/Exec.png", pos: "53% 5%", fit: "cover" },
  "Exploit": "art/Exploit.png",
  "Fault": "art/Fault.png",
  "Fiber": { src: "art/Fiber.png", pos: "73% 4%", fit: "cover" },
  "Firewall": "art/Firewall.png",
  "Flag": "art/Flag.png",
  "Forkbomb": { src: "art/Forkbomb.png", pos: "50% 50%", fit: "contain" },
  "Guard": "art/Guard.png",
  "HalfClone": "art/HalfClone.png",
  "Heap": "art/Heap.png",
  "Hivemind": "art/Hivemind.png",
  "Honeypot": "art/Honeypot.png",
  "Hook": "art/Hook.png",
  "Hotfix": "art/Hotfix.png",
  "Idle": "art/Idle.png",
  "Inline": { src: "art/Inline.png", pos: "50% 50%", fit: "contain" },
  "Int": "art/Int.png",
  "Interrupt": { src: "art/Interrupt.png", pos: "65% 42%", fit: "cover" },
  "JIT": "art/JIT.png",
  "Join": "art/Join.png",
  "Journal": "art/Journal.png",
  "Jump": "art/Jump.png",
  "Kernel": { src: "art/Kernel.png", pos: "65% 49%", fit: "cover" },
  "Lambda": "art/Lambda.png",
  "Latch": "art/Latch.png",
  "Livelock": { src: "art/Livelock.png", pos: "95% 74%", fit: "cover" },
  "Longjmp": "art/Longjmp.png",
  "Loop": "art/Loop.png",
  "Mainframe": "art/Mainframe.png",
  "Marshal": "art/Marshal.png",
  "Merge": "art/Merge.png",
  "Mutex": "art/Mutex.png",
  "Noop": "art/Noop.png",
  "Null": "art/Null.png",
  "Offset": "art/Offset.png",
  "Overflow": { src: "art/Overflow.png", pos: "53% 7%", fit: "cover" },
  "Overlord": "art/Overlord.png",
  "Overrun": { src: "art/Overrun.png", pos: "56% 66%", fit: "cover" },
  "Page": "art/Page.png",
  "Panic": { src: "art/Panic.png", pos: "50% 52%", fit: "cover" },
  "Persist": { src: "art/Persist.png", pos: "50% 40%", fit: "cover" },
  "Pin": "art/Pin.png",
  "Pipe": "art/Pipe.png",
  "Pivot": "art/Pivot.png",
  "Polymorph": "art/Polymorph.png",
  "Pool": "art/Pool.png",
  "Predicate": "art/Predicate.png",
  "Preempt": { src: "art/Preempt.png", pos: "79% 50%", fit: "cover" },
  "Probe": "art/Probe.png",
  "Profiler": { src: "art/Profiler.png", pos: "51% 92%", fit: "cover" },
  "ROM": "art/ROM.png",
  "Race": { src: "art/Race.png", pos: "36% 53%", fit: "contain" },
  "Raycast": "art/Raycast.png",
  "Recursion": { src: "art/Recursion.png", pos: "59% 36%", fit: "cover" },
  "Register": "art/Register.png",
  "Relay": "art/Relay.png",
  "Replica": "art/Replica.png",
  "Reroute": "art/Reroute.png",
  "Ripple": "art/Ripple.png",
  "Salvo": { src: "art/Salvo.png", pos: "30% 42%", fit: "contain" },
  "Sandbox": "art/Sandbox.png",
  "Scheduler": "art/Scheduler.png",
  "Semaphore": "art/Semaphore.png",
  "Sentinel": "art/Sentinel.png",
  "Signal": "art/Signal.png",
  "Singleton": "art/Singleton.png",
  "Singularity": "art/Singularity.png",
  "Snapshot": "art/Snapshot.png",
  "Sonar": "art/Sonar.png",
  "Spike": { src: "art/Spike.png", pos: "50% 50%", fit: "contain" },
  "Spooler": "art/Spooler.png",
  "Stack": "art/Stack.png",
  "Stub": "art/Stub.png",
  "Sudo": "art/Sudo.png",
  "Surge": { src: "art/Surge.png", pos: "42% 67%", fit: "contain" },
  "Sweeper": "art/Sweeper.png",
  "Switch": "art/Switch.png",
  "Symlink": "art/Symlink.png",
  "TLS": { src: "art/TLS.png", pos: "87% 39%", fit: "cover" },
  "Thrash": "art/Thrash.png",
  "Token1": "art/Token.png",
  "Token2": "art/Token2.png",
  "Token21": "art/Token2.png",
  "Token2b": "art/Token2b.png",
  "Token5": "art/Token5.png",
  "Trap": "art/Trap.png",
  "Value": "art/Value.png",
  "Var": "art/Var.png",
  "Vector": "art/Vector.png",
  "Wall10": "art/Wall10.png",
  "Wall8": "art/Wall8.png",
  "Ward": "art/Ward.png",
  "Watchdog": "art/Watchdog.png",
  "Worker": { src: "art/Worker.png", pos: "36% 47%", fit: "contain" },
  "Wormhole": "art/Wormhole.png",
  "Zygote": { src: "art/Zygote.png", pos: "54% 25%", fit: "cover" },
  "__body0": "art/__body0.png",
  "__body1": "art/__body1.png",
  "amplify()": "art/amplify_fn.png",
  "assert()": "art/assert_fn.png",
  "barrier()": "art/barrier_fn.png",
  "bind()": "art/bind_fn.png",
  "boost()": { src: "art/boost_fn.png", pos: "50% 50%", fit: "contain" },
  "burst()": { src: "art/burst_fn.png", pos: "77% 64%", fit: "cover" },
  "cast()": "art/cast_fn.png",
  "catch()": "art/catch_fn.png",
  "chain()": "art/chain_fn.png",
  "clear()": "art/clear_fn.png",
  "coalesce()": { src: "art/coalesce_fn.png", pos: "55% 30%", fit: "cover" },
  "compact()": "art/compact_fn.png",
  "copy()": "art/copy_fn.png",
  "crash()": { src: "art/crash_fn.png", pos: "78% 71%", fit: "cover" },
  "defer()": "art/defer_fn.png",
  "defrag()": "art/defrag_fn.png",
  "drop()": "art/drop_fn.png",
  "echo()": "art/echo_fn.png",
  "exit()": "art/exit_fn.png",
  "fanout()": "art/fanout_fn.png",
  "flush()": "art/flush_fn.png",
  "fork()": { src: "art/fork_fn.png", pos: "25% 75%", fit: "contain" },
  "fortify()": "art/fortify_fn.png",
  "free()": "art/free_fn.png",
  "freeze()": "art/freeze_fn.png",
  "glitch()": "art/glitch_fn.png",
  "goto()": "art/goto_fn.png",
  "grep()": "art/grep_fn.png",
  "halt()": "art/halt_fn.png",
  "hop()": "art/hop_fn.png",
  "inject()": "art/inject_fn.png",
  "jitter()": "art/jitter_fn.png",
  "jolt()": { src: "art/jolt_fn.png", pos: "45% 51%", fit: "contain" },
  "kill()": "art/kill_fn.png",
  "lock()": "art/lock_fn.png",
  "log()": "art/log_fn.png",
  "malloc()": "art/malloc_fn.png",
  "memcpy()": "art/memcpy_fn.png",
  "mend()": "art/mend_fn.png",
  "migrate()": { src: "art/migrate_fn.png", pos: "50% 50%", fit: "contain" },
  "mmap()": "art/mmap_fn.png",
  "mprotect()": "art/mprotect_fn.png",
  "overclock()": { src: "art/overclock_fn.png", pos: "57% 50%", fit: "cover" },
  "overtime()": "art/overtime.png",
  "patch()": "art/patch_fn.png",
  "ping()": "art/ping_fn.png",
  "pipeline()": "art/pipeline_fn.png",
  "proxy()": "art/proxy_fn.png",
  "pull()": "art/pull_fn.png",
  "purge()": "art/purge_fn.png",
  "push()": "art/push_fn.png",
  "reap()": { src: "art/reap_fn.png", pos: "30% 59%", fit: "contain" },
  "reflect()": "art/reflect_fn.png",
  "restore()": "art/restore_fn.png",
  "retry()": { src: "art/retry_fn.png", pos: "50% 50%", fit: "contain" },
  "rotate()": "art/rotate_fn.png",
  "rush()": { src: "art/rush_fn.png", pos: "50% 50%", fit: "contain" },
  "segfault()": { src: "art/segfault_fn.png", pos: "59% 57%", fit: "cover" },
  "shift()": "art/shift_fn.png",
  "siphon()": "art/siphon_fn.png",
  "snipe()": "art/snipe_fn.png",
  "spawn()": { src: "art/spawn_fn.png", pos: "57% 9%", fit: "contain" },
  "splice()": "art/splice_fn.png",
  "strike()": "art/strike_fn.png",
  "suspend()": "art/suspend_fn.png",
  "swap()": "art/swap_fn.png",
  "swapfile()": "art/swapfile_fn.png",
  "sync()": "art/sync_fn.png",
  "throw()": "art/throw_fn.png",
  "trace()": "art/trace_fn.png",
  "volt()": { src: "art/volt_fn.png", pos: "50% 6%", fit: "cover" },
  "wait()": "art/wait_fn.png",
  "wall()": "art/wall_fn.png",
  "yield()": "art/yield_fn.png",
};
