/* RUNTIME TCG — 견본 덱(순수 데이터, seed decks v8 / v14.1 카드풀 정합). engine.js보다 먼저 로드할 것. */
(function () {
  function expand(spec) { var d = []; for (var i = 0; i < spec.length; i++) { for (var n = 0; n < spec[i][1]; n++) d.push(spec[i][0]); } return d; }
  window.RT_DECKS = {
    T1: { name: 'T1 · 순수 thread 어그로', cls: 'thread', cover: 'Hivemind', list: expand([['Fiber', 2], ['Daemon', 2], ['Predicate', 2], ['Race', 2], ['Signal', 2], ['Inline', 2], ['Salvo', 2], ['Exec', 2], ['Kernel', 2], ['Cond', 2], ['boost()', 2], ['overclock()', 2], ['crash()', 2], ['strike()', 2], ['Preempt', 1], ['Hivemind', 1]]) },
    T2: { name: 'T2 · thread 미드시너지', cls: 'thread', cover: 'Kernel', list: expand([['Fiber', 2], ['Daemon', 2], ['Kernel', 2], ['Predicate', 2], ['Cond', 2], ['Race', 2], ['Signal', 2], ['Surge', 2], ['Inline', 2], ['Salvo', 2], ['boost()', 2], ['Exec', 2], ['Interrupt', 2], ['Recursion', 2], ['overclock()', 1], ['rush()', 1]]) },
    T3: { name: 'T3 · thread 번개 버스트', cls: 'thread', cover: 'Spike', list: expand([['Fiber', 2], ['Daemon', 2], ['Race', 2], ['Signal', 2], ['Surge', 2], ['Cond', 2], ['Elif', 2], ['Salvo', 1], ['Worker', 2], ['Recursion', 2], ['Bit', 2], ['Preempt', 1], ['Interrupt', 2], ['crash()', 1], ['retry()', 1], ['Join', 2], ['Spike', 2]]) },
    T4: { name: 'T4 · thread 분신 스웜', cls: 'thread', cover: 'Forkbomb', list: expand([['Zygote', 2], ['Pool', 2], ['Forkbomb', 2], ['Cluster', 2], ['Daemon', 2], ['Kernel', 2], ['Compile', 2], ['spawn()', 2], ['fanout()', 2], ['coalesce()', 2], ['migrate()', 2], ['amplify()', 2], ['boost()', 2], ['strike()', 2], ['Broadcast', 1], ['Mainframe', 1]]) },
    M1: { name: 'M1 · memory 컨트롤', cls: 'memory', cover: 'Singleton', list: expand([['Cache', 2], ['Heap', 2], ['Stack', 2], ['Mutex', 2], ['Sentinel', 2], ['Watchdog', 1], ['Register', 2], ['Aegis', 2], ['Quarantine', 2], ['Bulwark', 2], ['Checksum', 1], ['free()', 2], ['lock()', 2], ['purge()', 2], ['restore()', 2], ['bind()', 1], ['Singleton', 1]]) },
    M2: { name: 'M2 · memory 요새', cls: 'memory', cover: 'Bedrock', list: expand([['Cache', 2], ['Heap', 2], ['Stack', 2], ['Persist', 2], ['Const', 2], ['Page', 2], ['Mutex', 2], ['Sweeper', 2], ['Latch', 2], ['Warden', 1], ['Sentry', 1], ['Checksum', 2], ['Sentinel', 1], ['Firewall', 1], ['mprotect()', 1], ['harden()', 1], ['bastion()', 1], ['Guard', 1], ['restore()', 1], ['Bedrock', 1]]) },
    M3: { name: 'M3 · memory 봉쇄 락다운', cls: 'memory', cover: 'Semaphore', list: expand([['Cache', 2], ['Const', 2], ['Semaphore', 2], ['Pin', 2], ['Collector', 1], ['Mutex', 2], ['Register', 2], ['Assert', 2], ['Fallback', 2], ['Checksum', 2], ['lock()', 2], ['freeze()', 2], ['purge()', 2], ['restore()', 2], ['bind()', 1], ['shield()', 1], ['Singleton', 1]]) },
    P1: { name: 'P1 · process 미드 템포', cls: 'process', cover: 'Morph', list: expand([['Profiler', 2], ['Morph', 2], ['Match', 2], ['Cron', 2], ['Cursor', 2], ['Longjmp', 2], ['Exploit', 2], ['Probe', 2], ['Offset', 2], ['Jump', 1], ['Async', 2], ['Reroute', 2], ['Honeypot', 2], ['Callback', 2], ['Dispatch', 2], ['Vector', 1]]) },
    P2: { name: 'P2 · process 포인터 콤보', cls: 'process', cover: 'Conduit', list: expand([['Hook', 2], ['Pipe', 2], ['Lambda', 2], ['Relay', 2], ['JIT', 2], ['Spooler', 2], ['Hotfix', 2], ['Cron', 2], ['glitch()', 2], ['Marshal', 2], ['chain()', 1], ['pull()', 2], ['trace()', 2], ['Probe', 1], ['Jump', 1], ['Cursor', 1], ['Conduit', 1], ['Singularity', 1]]) },
    P3: { name: 'P3 · process 변위 컨트롤', cls: 'process', cover: 'Wormhole', list: expand([['Thrash', 2], ['Reroute', 2], ['Offset', 2], ['Dispatch', 1], ['Honeypot', 2], ['Marshal', 2], ['Async', 2], ['pull()', 2], ['push()', 2], ['glitch()', 2], ['memcpy()', 2], ['splice()', 2], ['snipe()', 1], ['Raycast', 1], ['Probe', 2], ['chain()', 1], ['Wormhole', 1], ['Singularity', 1]]) },
    N1: { name: 'N1 · generic 굿스터프', cls: 'generic', cover: 'Overlord', list: expand([['Var', 2], ['Int', 2], ['Value', 2], ['Coerce', 2], ['Merge', 2], ['Delete', 2], ['Switch', 2], ['kill()', 2], ['throw()', 2], ['halt()', 2], ['assert()', 2], ['ping()', 2], ['patch()', 2], ['exit()', 1], ['Ripple', 1], ['Sudo', 1], ['Overlord', 1]]) },
    N2: { name: 'N2 · 다형 스위치 4클래스', cls: 'mixed', cover: 'Switch', list: expand([['Switch', 2], ['Duplex', 2], ['Toggle', 2], ['Adaptive', 2], ['Failover', 1], ['Morph', 1], ['Ternary', 2], ['Case', 2], ['Bit', 2], ['Int', 2], ['Coerce', 2], ['Merge', 2], ['Stub', 2], ['Sonar', 2], ['kill()', 1], ['Delete', 1], ['Var', 1], ['Polymorph', 1]]) },
    X1: { name: 'X1 · 혼합 어그로-템포', cls: 'mixed', cover: 'Daemon', list: expand([['Fiber', 2], ['Salvo', 2], ['Surge', 2], ['Sonar', 2], ['Profiler', 2], ['Cron', 2], ['Idle', 2], ['Bit', 2], ['Flag', 2], ['Daemon', 2], ['Kernel', 2], ['Worker', 2], ['Stub', 2], ['Reroute', 1], ['Preempt', 1], ['Dispatch', 1], ['Zygote', 1]]) },
    X2: { name: 'X2 · 혼합 통제-응징', cls: 'mixed', cover: 'Cannon', list: expand([['Mutex', 2], ['Heap', 2], ['Ward', 2], ['Watchdog', 2], ['Collector', 2], ['Marshal', 2], ['Profiler', 2], ['Loop', 2], ['Dispatch', 2], ['kill()', 2], ['lock()', 2], ['Sonar', 2], ['purge()', 1], ['freeze()', 1], ['Cannon', 1], ['Idle', 1], ['Stack', 1], ['Trap', 1]]) },
    X3: { name: 'X3 · 혼합 미드레인지', cls: 'mixed', cover: 'Panic', list: expand([['Fiber', 2], ['Daemon', 2], ['Race', 2], ['Surge', 2], ['Bit', 2], ['Heap', 2], ['Mutex', 2], ['Salvo', 1], ['Sonar', 2], ['Kernel', 1], ['Worker', 2], ['Preempt', 1], ['lock()', 2], ['Flag', 2], ['Spike', 1], ['Delete', 1], ['Stub', 1], ['Panic', 1], ['Polymorph', 1]]) },
    C1: { name: 'C1 · 혼합 저격-흡수', cls: 'mixed', cover: 'Cursor', list: expand([['Cursor', 2], ['Probe', 2], ['Profiler', 2], ['Marshal', 2], ['pull()', 2], ['push()', 2], ['Guard', 2], ['Warden', 2], ['Buffer', 2], ['Heap', 2], ['compact()', 1], ['bastion()', 1], ['kill()', 2], ['catch()', 2], ['sync()', 2], ['throw()', 1], ['Polymorph', 1]]) }
  };
})();
