/* RUNTIME TCG — 견본 덱(순수 데이터). engine.js보다 먼저 로드할 것. */
(function () {
  function expand(spec) { var d = []; for (var i = 0; i < spec.length; i++) { for (var n = 0; n < spec[i][1]; n++) d.push(spec[i][0]); } return d; }
  window.RT_DECKS = {
    T1: { name: 'T1 · 순수 thread 어그로', cls: 'thread', list: expand([['Fiber', 2], ['Daemon', 2], ['Worker', 2], ['Race', 2], ['Signal', 2], ['Inline', 2], ['Salvo', 2], ['Exec', 2], ['Kernel', 2], ['Recursion', 1], ['Interrupt', 1], ['boost()', 2], ['overclock()', 2], ['crash()', 2], ['strike()', 2], ['rush()', 1], ['Hivemind', 1]]) },
    T2: { name: 'T2 · thread 미드시너지', cls: 'thread', list: expand([['Fiber', 2], ['Daemon', 2], ['Kernel', 2], ['Compile', 2], ['Race', 2], ['Overflow', 2], ['Signal', 2], ['Exec', 2], ['Inline', 2], ['Worker', 2], ['boost()', 2], ['overclock()', 2], ['amplify()', 2], ['spawn()', 2], ['Mainframe', 1], ['Polymorph', 1]]) },
    M1: { name: 'M1 · memory 컨트롤', cls: 'memory', list: expand([['Cache', 2], ['Heap', 2], ['Stack', 2], ['Mutex', 2], ['Sentinel', 2], ['Watchdog', 2], ['Sweeper', 2], ['Register', 2], ['Firewall', 2], ['Buffer', 1], ['Persist', 2], ['free()', 2], ['lock()', 2], ['purge()', 2], ['restore()', 2], ['Singleton', 1]]) },
    M2: { name: 'M2 · memory 요새', cls: 'memory', list: expand([['Cache', 2], ['Heap', 2], ['Stack', 2], ['Firewall', 2], ['Const', 2], ['Persist', 2], ['Watchdog', 2], ['Sweeper', 2], ['Mutex', 2], ['Register', 2], ['Sentinel', 1], ['restore()', 2], ['compact()', 2], ['fortify()', 2], ['freeze()', 1], ['Bedrock', 1], ['Singleton', 1]]) },
    P1: { name: 'P1 · process 미드 템포', cls: 'process', list: expand([['Longjmp', 2], ['Raycast', 2], ['Exploit', 2], ['Jump', 2], ['Vector', 2], ['Profiler', 2], ['Callback', 2], ['Probe', 2], ['Hotfix', 1], ['Async', 1], ['snipe()', 2], ['chain()', 2], ['inject()', 2], ['pull()', 2], ['push()', 2], ['trace()', 1], ['Singularity', 1]]) },
    P2: { name: 'P2 · process 포인터 콤보', cls: 'process', list: expand([['Hook', 2], ['Pipe', 2], ['Lambda', 2], ['Relay', 2], ['Longjmp', 2], ['Profiler', 2], ['Probe', 2], ['Jump', 2], ['chain()', 2], ['snipe()', 2], ['pull()', 2], ['push()', 2], ['inject()', 2], ['trace()', 2], ['Conduit', 1], ['Singularity', 1]]) },
    N1: { name: 'N1 · generic 굿스터프', cls: 'generic', list: expand([['Byte', 2], ['Int', 2], ['Value', 2], ['Ripple', 2], ['Coerce', 2], ['Merge', 2], ['Delete', 2], ['Loop', 2], ['Stub', 2], ['Flag', 1], ['kill()', 2], ['ping()', 2], ['throw()', 2], ['assert()', 2], ['sync()', 1], ['malloc()', 1], ['Overlord', 1]]) },
    X1: { name: 'X1 · 혼합 thread/process', cls: 'mixed', list: expand([['Fiber', 2], ['Salvo', 2], ['Exec', 2], ['Race', 2], ['Longjmp', 2], ['Raycast', 2], ['Jump', 2], ['Exploit', 2], ['boost()', 2], ['crash()', 2], ['snipe()', 2], ['chain()', 2], ['kill()', 2], ['ping()', 2], ['throw()', 2]]) },
    T3: { name: 'T3 · thread 번개 버스트', cls: 'thread', list: expand([['Fiber', 2], ['Spike', 2], ['Surge', 2], ['Race', 2], ['Daemon', 2], ['Worker', 2], ['Signal', 2], ['Inline', 2], ['Exec', 2], ['Salvo', 2], ['boost()', 2], ['volt()', 2], ['crash()', 2], ['overclock()', 2], ['strike()', 1], ['rush()', 1]]) },
    C1: { name: 'C1 · 혼합 저격·흡수', cls: 'mixed', list: expand([['Cursor', 2], ['Longjmp', 2], ['Raycast', 2], ['Profiler', 2], ['Trap', 2], ['Ward', 2], ['glitch()', 2], ['snipe()', 2], ['chain()', 2], ['volt()', 2], ['siphon()', 2], ['kill()', 2], ['ping()', 2], ['Probe', 1], ['Jump', 1], ['Singularity', 1], ['mend()', 1]]) }
  };
})();
