/* RUNTIME TCG — 견본 덱(순수 데이터, seed decks v8 / v14.1 카드풀 정합). engine.js보다 먼저 로드할 것. */
(function () {
  function expand(spec) { var d = []; for (var i = 0; i < spec.length; i++) { for (var n = 0; n < spec[i][1]; n++) d.push(spec[i][0]); } return d; }
  window.RT_DECKS = {
    T1: { name: 'T1 · 순수 thread 어그로', cls: 'thread', list: expand([['Fiber', 2], ['Daemon', 2], ['Predicate', 2], ['Race', 2], ['Signal', 2], ['Inline', 2], ['Salvo', 2], ['Exec', 2], ['Kernel', 2], ['Cond', 2], ['boost()', 2], ['overclock()', 2], ['crash()', 2], ['strike()', 2], ['Preempt', 1], ['Hivemind', 1]]) },
    T2: { name: 'T2 · thread 미드시너지', cls: 'thread', list: expand([['Fiber', 2], ['Daemon', 2], ['Kernel', 2], ['Predicate', 2], ['Cond', 2], ['Race', 2], ['Signal', 2], ['Surge', 2], ['Inline', 2], ['Salvo', 2], ['boost()', 2], ['overclock()', 2], ['Exec', 2], ['rush()', 2], ['Mainframe', 1], ['Preempt', 1]]) },
    T3: { name: 'T3 · thread 번개 버스트', cls: 'thread', list: expand([['Fiber', 2], ['Spike', 2], ['Surge', 2], ['Cond', 2], ['Daemon', 2], ['Worker', 2], ['Signal', 2], ['Preempt', 2], ['Exec', 2], ['Salvo', 2], ['boost()', 2], ['retry()', 2], ['crash()', 2], ['overclock()', 2], ['strike()', 1], ['rush()', 1]]) },
    T4: { name: 'T4 · thread 분신 스웜', cls: 'thread', list: expand([['Zygote', 2], ['Pool', 2], ['Forkbomb', 2], ['Cluster', 2], ['Daemon', 2], ['Kernel', 2], ['Compile', 2], ['spawn()', 2], ['fanout()', 2], ['coalesce()', 2], ['migrate()', 2], ['amplify()', 2], ['boost()', 2], ['strike()', 2], ['Broadcast', 1], ['Mainframe', 1]]) },
    M1: { name: 'M1 · memory 컨트롤', cls: 'memory', list: expand([['Cache', 2], ['Heap', 2], ['Stack', 2], ['Mutex', 2], ['Sentinel', 2], ['Watchdog', 2], ['Sweeper', 2], ['Register', 2], ['Firewall', 2], ['Canary', 2], ['free()', 2], ['lock()', 2], ['purge()', 2], ['restore()', 2], ['bind()', 1], ['Singleton', 1]]) },
    M2: { name: 'M2 · memory 요새', cls: 'memory', list: expand([['Cache', 3], ['Heap', 3], ['Stack', 3], ['Persist', 3], ['Const', 3], ['Page', 3], ['Mutex', 3], ['Sentinel', 1], ['Watchdog', 1], ['Sweeper', 1], ['Register', 1], ['mprotect()', 1], ['segfault()', 1], ['Bedrock', 1], ['Singleton', 1], ['Latch', 1]]) },
    M3: { name: 'M3 · memory 봉쇄 락다운', cls: 'memory', list: expand([['Cache', 2], ['Const', 2], ['Semaphore', 2], ['Pin', 2], ['Canary', 2], ['Collector', 2], ['Mutex', 2], ['Register', 2], ['lock()', 2], ['freeze()', 2], ['bind()', 2], ['purge()', 2], ['restore()', 2], ['Sweeper', 2], ['Singleton', 1], ['Bedrock', 1]]) },
    P1: { name: 'P1 · process 미드 템포', cls: 'process', list: expand([['Exploit', 2], ['Jump', 2], ['Profiler', 2], ['Callback', 1], ['Probe', 1], ['Offset', 1], ['snipe()', 1], ['chain()', 2], ['inject()', 2], ['pull()', 2], ['push()', 2], ['Async', 2], ['Marshal', 2], ['Dispatch', 2], ['Reroute', 2], ['Idle', 2], ['trace()', 1], ['Singularity', 1]]) },
    P2: { name: 'P2 · process 포인터 콤보', cls: 'process', list: expand([['Hook', 2], ['Pipe', 2], ['Lambda', 2], ['Relay', 2], ['Longjmp', 2], ['JIT', 2], ['Spooler', 2], ['Probe', 2], ['Jump', 2], ['chain()', 2], ['snipe()', 2], ['pull()', 2], ['defer()', 2], ['trace()', 2], ['Conduit', 1], ['Singularity', 1]]) },
    P3: { name: 'P3 · process 변위 컨트롤', cls: 'process', list: expand([['Thrash', 2], ['Reroute', 2], ['Offset', 2], ['Dispatch', 1], ['Honeypot', 2], ['Marshal', 2], ['Async', 2], ['pull()', 2], ['push()', 2], ['glitch()', 2], ['memcpy()', 2], ['splice()', 2], ['snipe()', 2], ['Raycast', 2], ['chain()', 1], ['Wormhole', 1], ['Singularity', 1]]) },
    N1: { name: 'N1 · generic 굿스터프', cls: 'generic', list: expand([['Var', 2], ['Int', 2], ['Value', 2], ['Ripple', 2], ['Coerce', 2], ['Merge', 2], ['Delete', 2], ['Loop', 2], ['Debug', 2], ['halt()', 2], ['kill()', 2], ['ping()', 2], ['throw()', 2], ['assert()', 2], ['Sudo', 1], ['Overlord', 1]]) },
    N2: { name: 'N2 · generic 다형 4클래스', cls: 'generic', list: expand([['Switch', 2], ['Loop', 2], ['Coerce', 2], ['Value', 2], ['Int', 2], ['Ripple', 2], ['Fiber', 2], ['Race', 2], ['Mutex', 2], ['Canary', 2], ['Longjmp', 2], ['Branch', 2], ['kill()', 2], ['ping()', 2], ['Polymorph', 1], ['Overlord', 1]]) },
    X1: { name: 'X1 · 혼합 thread/process', cls: 'mixed', list: expand([['Fiber', 2], ['Salvo', 2], ['Exec', 2], ['Race', 2], ['Affinity', 2], ['Longjmp', 1], ['Raycast', 1], ['Jump', 2], ['Stub', 2], ['Idle', 2], ['Value', 2], ['Bit', 2], ['Sonar', 2], ['boost()', 1], ['crash()', 1], ['chain()', 1], ['snipe()', 1], ['kill()', 1], ['Polymorph', 1]]) },
    X2: { name: 'X2 · 혼합 봉쇄-응징 M×P', cls: 'mixed', list: expand([['Fault', 1], ['Thrash', 1], ['pull()', 2], ['Cache', 2], ['Semaphore', 2], ['Canary', 2], ['Collector', 2], ['lock()', 2], ['freeze()', 2], ['bind()', 2], ['restore()', 2], ['halt()', 2], ['siphon()', 2], ['free()', 2], ['Watchdog', 1], ['Cannon', 1], ['Singleton', 1], ['Snapshot', 1]]) },
    X3: { name: 'X3 · 혼합 미드레인지 T×M', cls: 'mixed', list: expand([['Fiber', 2], ['Daemon', 2], ['Race', 2], ['Surge', 2], ['Zygote', 2], ['Panic', 2], ['Kernel', 2], ['Heap', 2], ['Mutex', 2], ['restore()', 2], ['boost()', 2], ['Salvo', 2], ['Spike', 2], ['strike()', 3], ['Preempt', 1]]) },
    C1: { name: 'C1 · 혼합 저격·흡수', cls: 'mixed', list: expand([['Cursor', 1], ['Longjmp', 2], ['Profiler', 2], ['Trap', 2], ['Ward', 2], ['glitch()', 2], ['snipe()', 2], ['chain()', 2], ['catch()', 2], ['siphon()', 2], ['kill()', 1], ['Loop', 2], ['Sonar', 1], ['Stub', 1], ['Probe', 1], ['Jump', 1], ['Bit', 2], ['Singularity', 1], ['Polymorph', 1]]) }
  };
})();
